---
name: ci
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version'
        # Default value if no value is explicitly provided
        default: '2.3.0.2'
        # Input has to be provided for the workflow to run
        required: true
      ls:
        description: 'ls'
        default: 'ls-1'
        required: true

jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: echo "tag=${{ github.event.inputs.version }}-${{ github.event.inputs.ls }}" >> $GITHUB_ENV
      - name: Get current date
        id: date
        run: echo "name=$(date -u +%Y-%m-%dT%H%M%SZ)" >> $GITHUB_ENV
      - run: echo "repo_name=${{ github.repository.name }}" >> $GITHUB_ENV
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME - $repo_name
        env:
          TAG_NAME: nightly-tag-${{ env.tag }}
          RELEASE_NAME: nightly-release-${{ env.tag }}
          repo_name: ${{ env.repo_name }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.tag }}
          release_name: ${{ env.tag }}
          draft: false
          prerelease: false  
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }} 
